##################################################################################################
# Ratings service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: user-management1
  labels:
    app: user-management1
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: user-management1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-management1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-management1
        version: v1
    spec:
      containers:
      - name: user-management1
        image: gcr.io/clearview-dev/user_management_service1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: password
---
