apiVersion: v1
kind: Service
metadata:
  name: auth-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: auth-service
spec:
  type: LoadBalancer
  ports:
  - port: 6565
    protocol: TCP
