apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: 2018-03-08T15:39:03Z
  generation: 3
  labels:
    run: auth-service
  name: auth-service
  namespace: default
  resourceVersion: "110387"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/auth-service
  uid: d49be73f-22e6-11e8-b703-42010a8a0060
spec:
  replicas: 1
  selector:
    matchLabels:
      run: auth-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: auth-service
    spec:
      containers:
      - image: gcr.io/clearview-dev/auth_service
        imagePullPolicy: Always
        name: auth-service
        ports:
        - containerPort: 6565
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-03-08T15:39:03Z
    lastUpdateTime: 2018-03-08T15:39:03Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
