---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "app-orb"
  namespace: "default"
  labels:
    app: "app-orb"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "app-orb"
  template:
    metadata:
      labels:
        app: "app-orb"
    spec:
      containers:
      - name: "orb"
        image: "gcr.io/clearview-dev/orb"
        ports:
          - containerPort: 9090
            protocol: TCP
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "app-orb-hpa"
  namespace: "default"
  labels:
    app: "app-orb"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "app-orb"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
